package com.uah.f1backend.configuration.common;

public class ColumnNameConstants {
    public static final String TEAM_ID = "id";
    public static final String TEAM_NAME = "name";
    public static final String TEAM_LOGO = "logo";
    public static final String TEAM_TWITTER = "twitter";
    public static final String COUNTRY_ID = "id";
    public static final String COUNTRY_CODE = "code";
    public static final String COUNTRY_NAME = "name";
    public static final String DRIVER_ID = "id";
    public static final String DRIVER_NAME = "name";
    public static final String DRIVER_LAST_NAME = "last_name";
    public static final String DRIVER_INITIAL = "initial";
    public static final String DRIVER_DORSAL = "dorsal";
    public static final String DRIVER_PHOTO = "photo";
    public static final String DRIVER_TWITTER = "twitter";
    public static final String DRIVER_ID_COUNTRY = "id_country";
    public static final String DRIVER_ID_TEAM = "id_team";
    public static final String CAR_ID = "id";
    public static final String CAR_TEAM_ID = "id_team";
    public static final String CAR_NAME = "name";
    public static final String CAR_CODE = "code";
    public static final String CAR_ERS_GAIN_SLOW = "ers_gain_slow";
    public static final String CAR_RS_GAIN_MEDIUM = "ers_gain_medium";
    public static final String CAR_ERS_GAIN_FAST = "ers_gain_fast";
    public static final String CAR_CONSUMPTION = "consumption";
    public static final String USER_ID = "id";
    public static final String USER_EMAIL = "username";
    public static final String USER_PASSWORD = "password";
    public static final String USER_NAME = "name";
    public static final String USER_LAST_NAME = "last_name";
    public static final String USER_USERNAME = "username";
    public static final String USER_ROLE = "role_id";
    public static final String USER_VALIDATED = "validated";
    public static final String CIRCUIT_ID = "id";
    public static final String CIRCUIT_NAME = "name";
    public static final String CIRCUIT_CITY = "city";
    public static final String CIRCUIT_COUNTRY = "id_country";
    public static final String CIRCUIT_LAPS = "laps";
    public static final String CIRCUIT_LENGTH = "length";
    public static final String CIRCUIT_IMAGE = "image";
    public static final String CIRCUIT_SLOW_TURNS = "slow_turns";
    public static final String CIRCUIT_MEDIUM_TURNS = "medium_turns";
    public static final String CIRCUIT_FAST_TURNS = "fast_turns";
}
