INSERT INTO country (id, code, country.name) VALUES
                                                           (1, 'AFG', 'Afghanistan'),
                                                           (2, 'ALB', 'Albania'),
                                                           (3, 'DZA', 'Algeria'),
                                                           (4, 'AND', 'Andorra'),
                                                           (5, 'AGO', 'Angola'),
                                                           (6, 'ATG', 'Antigua and Barbuda'),
                                                           (7, 'ARG', 'Argentina'),
                                                           (8, 'ARM', 'Armenia'),
                                                           (9, 'AUS', 'Australia'),
                                                           (10, 'AUT', 'Austria'),
                                                           (11, 'AZE', 'Azerbaijan'),
                                                           (12, 'BHS', 'Bahamas'),
                                                           (13, 'BHR', 'Bahrain'),
                                                           (14, 'BGD', 'Bangladesh'),
                                                           (15, 'BRB', 'Barbados'),
                                                           (16, 'BLR', 'Belarus'),
                                                           (17, 'BEL', 'Belgium'),
                                                           (18, 'BLZ', 'Belize'),
                                                           (19, 'BEN', 'Benin'),
                                                           (20, 'BTN', 'Bhutan'),
                                                           (21, 'BOL', 'Bolivia'),
                                                           (22, 'BIH', 'Bosnia and Herzegovina'),
                                                           (23, 'BWA', 'Botswana'),
                                                           (24, 'BRA', 'Brazil'),
                                                           (25, 'BRN', 'Brunei'),
                                                           (26, 'BGR', 'Bulgaria'),
                                                           (27, 'BFA', 'Burkina Faso'),
                                                           (28, 'BDI', 'Burundi'),
                                                           (29, 'KHM', 'Cambodia'),
                                                           (30, 'CMR', 'Cameroon'),
                                                           (31, 'CAN', 'Canada'),
                                                           (32, 'CPV', 'Cape Verde'),
                                                           (33, 'CAF', 'Central African Republic'),
                                                           (34, 'TCD', 'Chad'),
                                                           (35, 'CHL', 'Chile'),
                                                           (36, 'CHN', 'China'),
                                                           (37, 'COL', 'Colombia'),
                                                           (38, 'COM', 'Comoros'),
                                                           (39, 'COG', 'Congo (Congo-Brazzaville)'),
                                                           (40, 'CRI', 'Costa Rica'),
                                                           (41, 'HRV', 'Croatia'),
                                                           (42, 'CUB', 'Cuba'),
                                                           (43, 'CYP', 'Cyprus'),
                                                           (44, 'CZE', 'Czechia'),
                                                           (45, 'COD', 'Democratic Republic of the Congo'),
                                                           (46, 'DNK', 'Denmark'),
                                                           (47, 'DJI', 'Djibouti'),
                                                           (48, 'DMA', 'Dominica'),
                                                           (49, 'DOM', 'Dominican Republic'),
                                                           (50, 'ECU', 'Ecuador'),
                                                           (51, 'EGY', 'Egypt'),
                                                           (52, 'SLV', 'El Salvador'),
                                                           (53, 'GNQ', 'Equatorial Guinea'),
                                                           (54, 'ERI', 'Eritrea'),
                                                           (55, 'EST', 'Estonia'),
                                                           (56, 'SWZ', 'Eswatini'),
                                                           (57, 'ETH', 'Ethiopia'),
                                                           (58, 'FJI', 'Fiji'),
                                                           (59, 'FIN', 'Finland'),
                                                           (60, 'FRA', 'France'),
                                                           (61, 'GAB', 'Gabon'),
                                                           (62, 'GMB', 'Gambia'),
                                                           (63, 'GEO', 'Georgia'),
                                                           (64, 'DEU', 'Germany'),
                                                           (65, 'GHA', 'Ghana'),
                                                           (66, 'GRC', 'Greece'),
                                                           (67, 'GRD', 'Grenada'),
                                                           (68, 'GTM', 'Guatemala'),
                                                           (69, 'GIN', 'Guinea'),
                                                           (70, 'GNB', 'Guinea-Bissau'),
                                                           (71, 'GUY', 'Guyana'),
                                                           (72, 'HTI', 'Haiti'),
                                                           (73, 'HND', 'Honduras'),
                                                           (74, 'HUN', 'Hungary'),
                                                           (75, 'ISL', 'Iceland'),
                                                           (76, 'IND', 'India'),
                                                           (77, 'IDN', 'Indonesia'),
                                                           (78, 'IRN', 'Iran'),
                                                           (79, 'IRQ', 'Iraq'),
                                                           (80, 'IRL', 'Ireland'),
                                                           (81, 'ISR', 'Israel'),
                                                           (82, 'ITA', 'Italy'),
                                                           (83, 'CIV', 'Ivory Coast'),
                                                           (84, 'JAM', 'Jamaica'),
                                                           (85, 'JPN', 'Japan'),
                                                           (86, 'JOR', 'Jordan'),
                                                           (87, 'KAZ', 'Kazakhstan'),
                                                           (88, 'KEN', 'Kenya'),
                                                           (89, 'KIR', 'Kiribati'),
                                                           (90, 'KWT', 'Kuwait'),
                                                           (91, 'KGZ', 'Kyrgyzstan'),
                                                           (92, 'LAO', 'Laos'),
                                                           (93, 'LVA', 'Latvia'),
                                                           (94, 'LBN', 'Lebanon'),
                                                           (95, 'LSO', 'Lesotho'),
                                                           (96, 'LBR', 'Liberia'),
                                                           (97, 'LBY', 'Libya'),
                                                           (98, 'LIE', 'Liechtenstein'),
                                                           (99, 'LTU', 'Lithuania'),
                                                           (100, 'LUX', 'Luxembourg'),
                                                           (101, 'MDG', 'Madagascar'),
                                                           (102, 'MWI', 'Malawi'),
                                                           (103, 'MYS', 'Malaysia'),
                                                           (104, 'MDV', 'Maldives'),
                                                           (105, 'MLI', 'Mali'),
                                                           (106, 'MLT', 'Malta'),
                                                           (107, 'MHL', 'Marshall Islands'),
                                                           (108, 'MRT', 'Mauritania'),
                                                           (109, 'MUS', 'Mauritius'),
                                                           (110, 'MEX', 'Mexico'),
                                                           (111, 'FSM', 'Micronesia'),
                                                           (112, 'MDA', 'Moldova'),
                                                           (113, 'MCO', 'Monaco'),
                                                           (114, 'MNG', 'Mongolia'),
                                                           (115, 'MNE', 'Montenegro'),
                                                           (116, 'MAR', 'Morocco'),
                                                           (117, 'MOZ', 'Mozambique'),
                                                           (118, 'MMR', 'Myanmar'),
                                                           (119, 'NAM', 'Namibia'),
                                                           (120, 'NRU', 'Nauru'),
                                                           (121, 'NPL', 'Nepal'),
                                                           (122, 'NLD', 'Netherlands'),
                                                           (123, 'NZL', 'New Zealand'),
                                                           (124, 'NIC', 'Nicaragua'),
                                                           (125, 'NER', 'Niger'),
                                                           (126, 'NGA', 'Nigeria'),
                                                           (127, 'PRK', 'North Korea'),
                                                           (128, 'MKD', 'North Macedonia'),
                                                           (129, 'NOR', 'Norway'),
                                                           (130, 'OMN', 'Oman'),
                                                           (131, 'PAK', 'Pakistan'),
                                                           (132, 'PLW', 'Palau'),
                                                           (133, 'PSE', 'Palestine'),
                                                           (134, 'PAN', 'Panama'),
                                                           (135, 'PNG', 'Papua New Guinea'),
                                                           (136, 'PRY', 'Paraguay'),
                                                           (137, 'PER', 'Peru'),
                                                           (138, 'PHL', 'Philippines'),
                                                           (139, 'POL', 'Poland'),
                                                           (140, 'PRT', 'Portugal'),
                                                           (141, 'QAT', 'Qatar'),
                                                           (142, 'ROU', 'Romania'),
                                                           (143, 'RUS', 'Russia'),
                                                           (144, 'RWA', 'Rwanda'),
                                                           (145, 'KNA', 'Saint Kitts and Nevis'),
                                                           (146, 'LCA', 'Saint Lucia'),
                                                           (147, 'VCT', 'Saint Vincent and the Grenadines'),
                                                           (148, 'WSM', 'Samoa'),
                                                           (149, 'SMR', 'San Marino'),
                                                           (150, 'STP', 'Sao Tome and Principe'),
                                                           (151, 'SAU', 'Saudi Arabia'),
                                                           (152, 'SEN', 'Senegal'),
                                                           (153, 'SRB', 'Serbia'),
                                                           (154, 'SYC', 'Seychelles'),
                                                           (155, 'SLE', 'Sierra Leone'),
                                                           (156, 'SGP', 'Singapore'),
                                                           (157, 'SVK', 'Slovakia'),
                                                           (158, 'SVN', 'Slovenia'),
                                                           (159, 'SLB', 'Solomon Islands'),
                                                           (160, 'SOM', 'Somalia'),
                                                           (161, 'ZAF', 'South Africa'),
                                                           (162, 'KOR', 'South Korea'),
                                                           (163, 'SSD', 'South Sudan'),
                                                           (164, 'ESP', 'Spain'),
                                                           (165, 'LKA', 'Sri Lanka'),
                                                           (166, 'SDN', 'Sudan'),
                                                           (167, 'SUR', 'Suriname'),
                                                           (168, 'SWE', 'Sweden'),
                                                           (169, 'CHE', 'Switzerland'),
                                                           (170, 'SYR', 'Syria'),
                                                           (171, 'TJK', 'Tajikistan'),
                                                           (172, 'TZA', 'Tanzania'),
                                                           (173, 'THA', 'Thailand'),
                                                           (174, 'TLS', 'Timor-Leste'),
                                                           (175, 'TGO', 'Togo'),
                                                           (176, 'TON', 'Tonga'),
                                                           (177, 'TTO', 'Trinidad and Tobago'),
                                                           (178, 'TUN', 'Tunisia'),
                                                           (179, 'TUR', 'Turkey'),
                                                           (180, 'TKM', 'Turkmenistan'),
                                                           (181, 'TUV', 'Tuvalu'),
                                                           (182, 'UGA', 'Uganda'),
                                                           (183, 'UKR', 'Ukraine'),
                                                           (184, 'ARE', 'United Arab Emirates'),
                                                           (185, 'GBR', 'United Kingdom'),
                                                           (186, 'USA', 'United States of America'),
                                                           (187, 'URY', 'Uruguay'),
                                                           (188, 'UZB', 'Uzbekistan'),
                                                           (189, 'VUT', 'Vanuatu'),
                                                           (190, 'VAT', 'Vatican City'),
                                                           (191, 'VEN', 'Venezuela'),
                                                           (192, 'VNM', 'Vietnam'),
                                                           (193, 'YEM', 'Yemen'),
                                                           (194, 'ZMB', 'Zambia'),
                                                           (195, 'ZWE', 'Zimbabwe');

