-- MySQL Script generated by MySQL Workbench
-- Mon Oct 16 20:24:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema f1-agile
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema f1-agile
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `f1-agile` DEFAULT CHARACTER SET utf8 ;
USE `f1-agile` ;

-- -----------------------------------------------------
-- Table `f1-agile`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `f1-agile`.`team` ;

CREATE TABLE IF NOT EXISTS `f1-agile`.`team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `logo` LONGTEXT NULL,
  `twitter` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1-agile`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `f1-agile`.`country` ;

CREATE TABLE IF NOT EXISTS `f1-agile`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(3) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1-agile`.`driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `f1-agile`.`driver` ;

CREATE TABLE IF NOT EXISTS `f1-agile`.`driver` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `initial` VARCHAR(3) NOT NULL,
  `dorsal` VARCHAR(2) NOT NULL,
  `photo` LONGTEXT NULL,
  `id_country` INT NOT NULL,
  `twitter` VARCHAR(200) NULL,
  `id_team` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_driver_country_idx` (`id_country` ASC) VISIBLE,
  INDEX `fk_driver_team1_idx` (`id_team` ASC) VISIBLE,
  CONSTRAINT `fk_driver_country`
    FOREIGN KEY (`id_country`)
    REFERENCES `f1-agile`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_driver_team1`
    FOREIGN KEY (`id_team`)
    REFERENCES `f1-agile`.`team` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1-agile`.`track`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `f1-agile`.`track` ;

CREATE TABLE IF NOT EXISTS `f1-agile`.`track` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `id_country` INT NOT NULL,
  `image` LONGTEXT NULL,
  `laps` INT NOT NULL,
  `length` INT NOT NULL,
  `slow_turns` INT NOT NULL,
  `medium_turns` INT NOT NULL,
  `fast_turns` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_track_country1_idx` (`id_country` ASC) VISIBLE,
  CONSTRAINT `fk_track_country1`
    FOREIGN KEY (`id_country`)
    REFERENCES `f1-agile`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1-agile`.`car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `f1-agile`.`car` ;

CREATE TABLE IF NOT EXISTS `f1-agile`.`car` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `ers_gain_slow` DECIMAL NOT NULL,
  `ers_gain_medium` DECIMAL NOT NULL,
  `ers_gain_fast` DECIMAL NOT NULL,
  `consumption` DECIMAL NOT NULL,
  `id_team` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_car_team1_idx` (`id_team` ASC) VISIBLE,
  CONSTRAINT `fk_car_team1`
    FOREIGN KEY (`id_team`)
    REFERENCES `f1-agile`.`team` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
